exclude-labels:
  - 'Ignore for release'
  - 'Temp:IncludedInMainDraft'
include-labels:
  - 'bug'

name-template: 'ThingsBoard IoT Gateway v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
template: |
  $CHANGES

change-template: '* $TITLE (#$NUMBER) @$AUTHOR'

header: |
  ## 🐛 Bug fixes

category-template: '#### $TITLE'
categories:

  - title: '🐛 Core bug fixes'
    labels:
      - 'core'

  - title: '🐛 MQTT connector bug fixes'
    labels:
      - 'Connector:MQTT'

  - title: '🐛 Modbus connector bug fixes'
    labels:
      - 'Connector:Modbus'

  - title: '🐛 OPC-UA connector bug fixes'
    labels:
      - 'Connector:OPC-UA'

  - title: '🐛 BLE connector bug fixes'
    labels:
      - 'Connector:BLE'

  - title: '🐛 BACnet connector bug fixes'
    labels:
      - 'Connector:BACnet'

  - title: '🐛 KNX connector bug fixes'
    labels:
      - 'Connector:KNX'

  - title: '🐛 CAN connector bug fixes'
    labels:
      - 'Connector:CAN'

  - title: '🐛 FTP connector bug fixes'
    labels:
      - 'Connector:FTP'

  - title: '🐛 OCPP connector bug fixes'
    labels:
      - 'Connector:OCPP'

  - title: '🐛 ODBC connector bug fixes'
    labels:
      - 'Connector:ODBC'

  - title: '🐛 Request connector bug fixes'
    labels:
      - 'Connector:Request'

  - title: '🐛 REST connector bug fixes'
    labels:
      - 'Connector:REST'

  - title: '🐛 SNMP connector bug fixes'
    labels:
      - 'Connector:SNMP'

  - title: '🐛 Socket connector bug fixes'
    labels:
      - 'Connector:Socket'

  - title: '🐛 XMPP connector bug fixes'
    labels:
      - 'Connector:XMPP'

  - title: '🐛 Other bug fixes'
